name: CI

# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: .
        # The name of the storage account container these assets will be uploaded to
        container_name: 'mapdash' 
        # The connection string for the storage account
        connection_string: ${{ secrets.storage }}
        # extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`
        extra_args: # optional
